// Code generated by security audit. DO NOT EDIT.
// This file documents command injection prevention measures.

package server

/*
Command Injection Prevention Guidelines
======================================

This codebase does NOT use os/exec to execute external commands.
The following practices ensure command injection risks are minimized:

1. NO External Command Execution
   - No use of os/exec.Command
   - No use of syscall.Exec
   - No shell command construction

2. Safe File Operations
   - All file paths use filepath.Clean()
   - Path traversal is prevented in config/loader.go
   - File permissions are restricted (0o600 for sensitive files)

3. Safe Configuration Loading
   - YAML parsing uses gopkg.in/yaml.v3
   - No dynamic code execution from config
   - Config paths are validated before use

4. Input Validation
   - All user inputs are validated before use
   - SQL queries use parameterized statements
   - File paths are validated with filepath.Clean()

If future features require external command execution:

1. Use exec.Command with explicit arguments (NOT shell)
   BAD:  exec.Command("sh", "-c", userInput)
   GOOD: exec.Command("/usr/bin/valid_cmd", arg1, arg2)

2. Validate all arguments against whitelist
   - Use strict regex patterns
   - Reject any shell metacharacters

3. Use full paths to executables
   - Avoid PATH lookup
   - Verify executable exists and permissions

4. Never pass user input directly
   - Sanitize all inputs
   - Use parameterized approaches

5. Audit logging
   - Log all command executions
   - Include full command line for forensics

Security Contact
================
If you discover a potential command injection vulnerability,
please report it immediately following the security policy.
*/
